            - name: Build Quartz for GitHub Pages
  uses: konstfish/quartz-build-action@v6
  with:
    # The directory to build from (using default: ./)
    source: ./
    # The directory to write output into (using default: ./_site)
    destination: ./_site
    
    # Title of resulting Quartz Page
    page_title: "Jaden's University Notes"
    
    # Base URL (Required when setting icon or banner)
    page_base_url: https://JadenMajid.github.io/UniversityNotes/ # Leave empty to use the default or set your actual URL, e.g., https://<YOUR_USERNAME>.github.io/<YOUR_REPO>/
    
    # Path to custom Quartz config file
    # quartz_config:
    
    # Path to custom Quartz layout file
    # quartz_layout:
    
    # Path to custom Quartz Page icon (png)
    # quartz_icon:
    
    # Path to custom Quartz Page banner (png)
    # quartz_banner:
    
    # Path to custom Quartz Page css
    # quartz_custom_css:
